# code sequence features
NUMERIC_CONSTANT = 0
TRANSFER_INSTRUCTION = 1
CALL_INSTRUCTION = 2
ARITHMETIC_INSTRUCTION = 3
COMPARE_INSTRUCTION = 4
MOV_INSTRUCTION = 5
TERMINATION_INSTRUCTION = 6
DATA_DECLARATION_INSTRUCTION = 7

statement_type_map = {
    "<operator>.assignment": MOV_INSTRUCTION
}
